### ISSUE TITLE
Does not work on macOS Mojave

### ISSUE THREAD

**Issue by bludginozzie** [gjoseph/BarbaryWatchService#12]
The native library appears to be unsigned which prevents it working on macOS Mojave.  The following stacktrace appears.

`
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/2j/d0q_j4kx2bg1np_jsmb5sx6r0000gn/T/jna15911312554531815838.tmp: dlopen(/private/var/folders/2j/d0q_j4kx2bg1np_jsmb5sx6r0000gn/T/jna15911312554531815838.tmp, 1): no suitable image found.  Did find:
        /private/var/folders/2j/d0q_j4kx2bg1np_jsmb5sx6r0000gn/T/jna15911312554531815838.tmp: code signature in (/private/var/folders/2j/d0q_j4kx2bg1np_jsmb5sx6r0000gn/T/jna15911312554531815838.tmp) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
        at java.base/java.lang.Runtime.load0(Runtime.java:767)
        at java.base/java.lang.System.load(System.java:1831)
        at com.sun.jna.Native.loadNativeLibraryFromJar(Native.java:744)
        at com.sun.jna.Native.loadNativeLibrary(Native.java:678)
        at com.sun.jna.Native.<clinit>(Native.java:106)
        at com.barbarysoftware.jna.CarbonAPI.<clinit>(CarbonAPI.java:6)
        at com.barbarysoftware.jna.CFStringRef.toCFString(CFStringRef.java:10)
        at com.barbarysoftware.watchservice.MacOSXListeningWatchService.register(MacOSXListeningWatchService.java:30)
        at com.barbarysoftware.watchservice.WatchableFile.register(WatchableFile.java:30)
        at com.barbarysoftware.watchservice.WatchableFile.register(WatchableFile.java:39)
        .....
`

**Comment by gjoseph** [comment]
Hi @bludginozzie sorry for the slow response -- as you may have gathered, I haven't had capacity to maintain this project in a _long_ time. I'm finally officially retiring it. See README for possible alternatives, if you're still needing this. ✌️
